export { createSession } from "./dom-host.js";
export type { Session, SessionOptions } from "./dom-host.js";
export { preset, PRESETS, applyProfile, validateProfile, profileHeaders } from "./device-profile.js";
export type { DeviceProfile, UaBrand } from "./device-profile.js";
export { PinnedCdn, LiveCdn, VersionFetchFailed } from "./clarity-provider.js";
export type { ClarityBundleProvider } from "./clarity-provider.js";
export { installShims, assertReady } from "./shims.js";
export { installGeometryOracle } from "./geometry.js";
export type { Box, GeometryMap, GeometryOptions } from "./geometry.js";
export { installTransport } from "./transport.js";
export type { UploadRecord, TransportOptions } from "./transport.js";
export { loadBundle, authorBundle, validateBundle, writeBundle } from "./bundle.js";
export type { LoadedBundle, BundleManifest, GeometryMode, AuthorOptions } from "./bundle.js";
