export { createSession } from "./dom-host.js";
export type { Session, SessionOptions } from "./dom-host.js";
export { preset, PRESETS, applyProfile, validateProfile, profileHeaders } from "./device-profile.js";
export type { DeviceProfile, UaBrand } from "./device-profile.js";
export { PinnedCdn, LiveCdn, VersionFetchFailed, parseTagConfig } from "./clarity-provider.js";
export type { ClarityBundleProvider, TagConfig } from "./clarity-provider.js";
export { installShims, assertReady } from "./shims.js";
export { installGeometryOracle } from "./geometry.js";
export type { Box, GeometryMap, GeometryOptions } from "./geometry.js";
export { installTransport } from "./transport.js";
export type { UploadRecord, TransportOptions } from "./transport.js";
export { loadBundle, authorBundle, validateBundle, writeBundle } from "./bundle.js";
export type { LoadedBundle, BundleManifest, GeometryMode, AuthorOptions } from "./bundle.js";
export { scenario, ScenarioBuilder } from "./scenario.js";
export type { Scenario, Step } from "./scenario.js";
export { runScenario } from "./runner.js";
export { run } from "./run.js";
export type { RunRequest, SessionResult, Verdict, ProxyConfig } from "./run.js";
export { socksDispatcher, parseSocks } from "./socks.js";
export { Rng } from "./prng.js";
export { decimate, mousePath, clickPlacement, typingPlan, pickArchetype, ARCHETYPES } from "./realism.js";
export type { PathPoint, KeyPlan, ArchetypeName } from "./realism.js";
